In [80]:
import os
import pandas as pd

In [70]:
food_names = pd.read_csv(
    "../datasets/food-101/meta/classes.txt",
    header=None,
    names=["food_name"]
)

food_names.head()

        food_name
0       apple_pie
1  baby_back_ribs
2         baklava
3  beef_carpaccio
4    beef_tartare

In [71]:
food_names.shape

(101, 1)

In [72]:
food_names["calories_per_100g"] = None
food_names["protein_g_per_100g"] = None
food_names["fat_g_per_100g"] = None
food_names["carbs_g_per_100g"] = None
food_names["fiber_g_per_100g"] = None
food_names["sugar_g_per_100g"] = None
food_names["sodium_mg_per_100g"] = None

food_names.head()

,food_name,calories_per_100g,protein_g_per_100g,fat_g_per_100g,carbs_g_per_100g,fiber_g_per_100g,sugar_g_per_100g,sodium_mg_per_100g
0,apple_pie,None,None,None,None,None,None,None
1,baby_back_ribs,None,None,None,None,None,None,None
2,baklava,None,None,None,None,None,None,None
3,beef_carpaccio,None,None,None,None,None,None,None
4,beef_tartare,None,None,None,None,None,None,None

In [73]:
food_names.to_csv("../datasets/nutrition.csv", index=False)

In [ ]:
food_names.head()

,food_name,calories_per_100g,protein_g_per_100g,fat_g_per_100g,carbs_g_per_100g,fiber_g_per_100g,sugar_g_per_100g,sodium_mg_per_100g
0,apple_pie,None,None,None,None,None,None,None
1,baby_back_ribs,None,None,None,None,None,None,None
2,baklava,None,None,None,None,None,None,None
3,beef_carpaccio,None,None,None,None,None,None,None
4,beef_tartare,None,None,None,None,None,None,None

In [82]:
df = pd.read_csv("../datasets/nutrition.csv")

In [83]:
df.head()

,food_name,calories_per_100g,protein_g_per_100g,fat_g_per_100g,carbs_g_per_100g,fiber_g_per_100g,sugar_g_per_100g,sodium_mg_per_100g
0,apple_pie,237,2.4,11.0,34.0,1.5,19.0,180
1,baby_back_ribs,280,22.0,20.0,2.0,0.0,1.0,450
2,baklava,428,6.0,21.0,56.0,2.5,38.0,190
3,beef_carpaccio,130,22.0,5.0,1.0,0.0,0.0,350
4,beef_tartare,170,20.0,9.0,2.0,0.0,1.0,400

In [78]:
df.isnull().sum()

food_name             0
calories_per_100g     0
protein_g_per_100g    0
fat_g_per_100g        0
carbs_g_per_100g      0
fiber_g_per_100g      0
sugar_g_per_100g      0
sodium_mg_per_100g    0
dtype: int64